[workspace]
members = ["turtle-entities", "turtle-server", "turtle-tui", "turtle-types"]
resolver = "3"

[workspace.dependencies]
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
thiserror = "2.0.9"
tokio = "1.44.0"
futures = "0.3.31"
serde = "1.0.217"
serde_json = "1.0.135"
chrono = "0.4.40"

kameo = "0.19.0"
kameo_actors = "0.4.0"

axum = { version = "0.8.5", features = ["ws", "macros"] }
axum-extra = { version = "0.10.0", features = ["typed-header"] }
tokio-tungstenite = "0.26.0"
tower-http = { version = "0.6.1", features = ["fs", "trace"] }

sea-orm = { version = "2.0.0-rc.16", features = [
  "runtime-tokio-rustls",
  "sqlx-sqlite",
  "macros",
  "schema-sync",
  "entity-registry",
  # "debug-print",
] }

sea-orm-migration = { version = "2.0.0-rc.16", features = [] }
