[package]
name = "turtle-wrangler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
thiserror = "2.0.9"
tokio = { version = "1.43.0", features = ["full"] }
futures = "0.3.31"
serde = "1.0.217"
serde_json = "1.0.135"
sqlx = "0.8.3"

kameo = "0.13.0"

axum = { version = "0.8.1", features = ["ws"] }
axum-extra = { version = "0.10.0", features = ["typed-header"] }
tokio-tungstenite = "0.26.0"
tower-http = { version = "0.6.1", features = ["fs", "trace"] }
