//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.16

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "turtle")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique, indexed)]
    pub name: String,
    // #[sea_orm(ignore, column_type = "custom(\"enum_text\")", select_as = "text")]
    pub turtle_type: turtle_types::turtle_scheme::TurtleType,
    pub fuel: i32,
    pub x: i32,
    pub y: i32,
    pub z: i32,
    // #[sea_orm(ignore, column_type = "custom(\"enum_text\")", select_as = "text")]
    pub heading: turtle_types::turtle_scheme::Heading,
    #[sea_orm(default_value = "Default::default()")]
    pub inventory: turtle_types::turtle_scheme::TurtleInventory,
    // pub selected_slot: u8,
    // pub items: HasOne<super::turtle_inventory::Model>,
    pub last_seen: DateTimeUtc,
}

impl ActiveModelBehavior for ActiveModel {}
